<a href="https://colab.research.google.com/github/kdemertzis/EKPA/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [ ]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0               icloud.coms.my.id        0        0           0          1   
1                      tobogo.net        0        0           1          2   
2                 cheezburger.com        0        0           1          2   
3  firebasestorage.googleapis.com        0        1           1          5   
4    securemail9.godaddysites.com        0        0           0          0   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              0           0            1   
1            0             0        0              0           0            1   
2            0             0        0              0           0            1   
3            0             0        1              0           1            1   
4            0             0        0              0           0            1   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           0           1       0           0            1             0   
1           0           0       0           0            1             0   
2           0           1       0           0            1             0   
3           1           1       0           0            1             0   
4           0           1       0           0            1             0   

   Label  
0      1  
1      0  
2      0  
3      1  
4      1

In [ ]:
X = data.drop(['Domain', 'Label'], axis=1)

In [ ]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           0          1            0             0   
1        0        0           1          2            0             0   
2        0        0           1          2            0             0   
3        0        1           1          5            0             0   
4        0        0           0          0            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           0           1   
1        0              0           0            1           0           0   
2        0              0           0            1           0           1   
3        1              0           1            1           1           1   
4        0              0           0            1           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [ ]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [ ]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [ ]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8026666666666666
Precision: 0.8247380908701768
Recall: 0.8026666666666666
F1 Score: 0.7991664555052791
Confusion Matrix:
[[1404  100]
 [ 492 1004]]

SVC Metrics:
Accuracy: 0.8363333333333334
Precision: 0.8680694582861227
Recall: 0.8363333333333334
F1 Score: 0.832649995830681
Confusion Matrix:
[[1479   25]
 [ 466 1030]]

RandomForestClassifier Metrics:
Accuracy: 0.8656666666666667
Precision: 0.8728607880411734
Recall: 0.8656666666666667
F1 Score: 0.8649861707177328
Confusion Matrix:
[[1407   97]
 [ 306 1190]]

MLPClassifier Metrics:
Accuracy: 0.8443333333333334
Precision: 0.8502018914533831
Recall: 0.8443333333333334
F1 Score: 0.8436455100545003
Confusion Matrix:
[[1368  136]
 [ 331 1165]]

KNeighborsClassifier Metrics:
Accuracy: 0.8373333333333334
Precision: 0.8431394268476621
Recall: 0.8373333333333334
F1 Score: 0.8366073023884665
Confusion Matrix:
[[1358  146]
 [ 342 1154]]

DecisionTreeClassifier Metrics:
Accuracy: 0.863
Precision: 0.87056655

In [ ]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.865667   0.872861  0.865667  0.864986
5  DecisionTreeClassifier  0.863000   0.870567  0.863000  0.862266
3           MLPClassifier  0.844333   0.850202  0.844333  0.843646
4    KNeighborsClassifier  0.837333   0.843139  0.837333  0.836607
1                     SVC  0.836333   0.868069  0.836333  0.832650
0      LogisticRegression  0.802667   0.824738  0.802667  0.799166
